# Generated by Django 3.1.4 on 2020-12-27 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forexPredict', '0002_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
